### ISSUE TITLE
Is it possible to use an externally provided stream?

### ISSUE THREAD

**Issue by burlen** [icl-utk-edu/blaspp#14]
I'm working on a code that makes use of multiple GPU accelerated numerical libraries. Each of these has the ability to pass a CUDA stream that can be used to ensure correct order of operations without unnecessary synchronization when sharing device data between calls. BLAS++ (in its Queue object) uses an internally managed stream which is leading to additional synchronization overheads when interoperating with other libraries. I see no API to pass an existing stream into BLAS++.  Is it possible to tell BLAS++ which stream to use? Is that a use case the could be supported?

**Comment by mgates3** [comment]
We have some work on this (in our old bitbucket repo): https://bitbucket.org/icl/blaspp/pull-requests/43

It needs some more work to deal with batch routines, which in some cases need additional streams.

Does that look like it would satisfy your needs?

**Comment by rileyjmurray** [comment]
@mgates3 is there any hope of getting the PR you linked merged into BLAS++ sometime soon? I ask because we're running into this issue with RandBLAS(@burlen is leading our GPU development).

**Comment by burlen** [comment]
also, we do not need blaspp to create many streams for batching. since we'd not use that feature, ideally blaspp would not create those unless requested.

**Comment by mgates3** [comment]
Yes, this is next up. We did a lot of refactoring to make code modifications simpler (instead of repeating the same mod 4x for 4 precisions).

**Comment by mgates3** [comment]
See PR #38. A Queue has only 1 stream initially, and allocates workspace and additional streams as needed.

**Comment by mgates3** [comment]
Fixed by PR #38.
