### ISSUE TITLE
Device `blas::axpy` does not have `const` modifier on `x`

### ISSUE THREAD

**Issue by PTNobel** [icl-utk-edu/blaspp#20]
Hello all,

The API for `blas::axpy` on the CPU is:
```
void axpy(
    int64_t n,
    double alpha,
    double const *x, int64_t incx,
    double       *y, int64_t incy )
```
with a const on `x`.

However, the device version has API:
```
void blas::axpy(
    int64_t n,
    double alpha,
    double *dx, int64_t incdx,
    double *dy, int64_t incdy,
    blas::Queue& queue)
```
which lacks the `const` modifier on `dx`.

Would it be possible to add it? I would prefer to have symmetry in my device and CPU implementation. Is there concerns that `dx` may be modified?

FYI, this work is part of @BallisticLA. I'm not sure where that falls into the ECP.

**Comment by mgates3** [comment]
Thanks, we will review and update it.
