### ISSUE TITLE
Running on CPU when configured with CUBLAS

### ISSUE THREAD

**Issue by NamjaeChoi** [icl-utk-edu/blaspp#94]
Hello Slate team,

We are using Slate through PETSc which is the computational backend of MOOSE, and we always want to configure PETSc with CUDA to make a unified container for all of our environments. However, we are noticing that PETSc configured with CUDA does not run on a non-GPU environment (no CUDA driver) as Slate is attempting to query the number of devices whenever it is configured with cuBLAS.

Is it possible to allow Slate to run on CPUs even when it is configured with cuBLAS? In other words, I wonder if it would be harmful to add a third condition of not detecting the driver in `device_utils.cc:get_device_count`?

Thanks.

**Comment by mgates3** [comment]
Perhaps instead of
```c++
        auto err = cudaGetDeviceCount(&dev_count);
        if (err != cudaSuccess && err != cudaErrorNoDevice)
            blas_dev_call( err );
```
it should just be:
```c++
        auto err = cudaGetDeviceCount(&dev_count);
        if (err != cudaSuccess)
            dev_count = 0;
```
That is, any error is treated as "no GPUs available".

**Comment by NamjaeChoi** [comment]
That seems like a good change. Will it fallback to CPUs when no GPU is available?

**Comment by mgates3** [comment]
Yes, SLATE can use CPUs only. Currently, it depends on what `Target` is used when calling SLATE. There is no `Target::Auto` that would automatically use GPUs if available, else CPUs. We are working on that, but it hasn't been merged in yet. I will make this change in BLAS++ so SLATE can work if compiled for CUDA but CUDA is not installed. (Most of our systems have CUDA installed, even if they don't have CUDA GPUs, so this case never got tested.)

**Comment by NamjaeChoi** [comment]
Okay, thank you for letting me know.

**Comment by NamjaeChoi** [comment]
Hello, thank you for addressing this issue. Do you have any plans to incorporate it into Slate and release the next Slate version?

**Comment by mgates3** [comment]
I don't think there are any backward-incompatible changes, so you should be able to use this version of BLAS++ with SLATE. If you use submodules, you would have to go into the blaspp submodule to checkout the latest. When we do a new release of SLATE, we will definitely update to the latest BLAS++.
